### ISSUE TITLE
Create API endpoint to persist Workspace

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#100]
Need a CRUD REST API endpoint for the [Workspace data structure](https://github.com/SciGaP/simccs-maptool/wiki/Build-Tool:-Workspace).

### TODO

- [x] create scenarios
- [x] create sources and sinks associated with scenario
- [x] create the experiments associated with scenario
- [x] add/update scenarios
- [x] add/update sources and sinks associated with scenario
- [x] add/update experiments associated with scenario
- [x] add derived fields to experiment serializer (experiment name, url, state, result)
- [x] integrate with UI - save_workspace
- [x] -handle source and sink fields - maybe derive them from the geojson file?- for now ids are sufficient
- [x] validate unique workspace name and unique scenario title
- [x] (maybe separate issue) when creating experiment for a workspace, it should be created in the Airavata project that belongs to the Case's SimCCS Project
- [x] add created/updated date to workspace
