### ISSUE TITLE
Rename the shapefiles

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#142]
The shapefiles all have the same names, so downloading them from several experiments/scenarios results in a bunch of files that are indistinguishable by name. The user must manually rename all of these files to keep them distinct.

Can we rename the shapefiles based on the scenario?  Maybe something similar to how renaming the mps file works: https://github.com/SciGaP/simccs-maptool/commit/917263c7a565b6216cc455fa6c0f526bdcca5400

#### TODO

- [x] add download experiments endpoint to the SDK
- [x] support include and exclude patterns
- [x] support rename operations
- [x] integrate into the build tool for downloading experiment shapefiles

**Comment by machristie** [comment]
Created Jira issue to track the download experiments endpoint that is being added to the SDK https://issues.apache.org/jira/browse/AIRAVATA-3542
