### ISSUE TITLE
calculate and display candidate network

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#28]
### TODO

- [x] Generate the candidate network shapefile
- [x] convert shapefile to GeoJSON
- [x] display on map for the selected sources and sinks when button is clicked
- [x] make available in separate toggle-able layer
- [x] validate that at least one source and one sink are selected
- [x] also for the use case editing
