### ISSUE TITLE
Cloned experiments don't show results

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#52]
Cloning experiments doesn't preserve the expected scenario directory structure.

Here are some ideas:

- have the input and output files in a flat directory structure but within that directory, create the expected scenario directory structure using symlinks. For example:
  - exp data dir:
    - mip.mps - real input file
    - soln.sol - real output file
    - ... - additional needed real input files
    - Dataset
      - BaseData - symlink to global BaseData directory
      - Scenarios
         - scenario1
            - Results, Sinks, etc. directories, with appropriate symlinks to files in the top level exp data dir
- register Sinks.txt, Sources.txt, Linear.txt, etc. other input files that are needed so that they are cloned too. Currently only the mps file is cloned.
- we might need an additional file to specify the base dataset

# TODOS
- [x] create new CPLEX application with Sources, Sinks, Transport, Candidate Network, MPS and Dataset ID as inputs. Dataset ID should be readonly.
- [x] new generate_mps function that users a temporary directory for the scenario directory and uploads sources, sinks, transport and mps file into user's tmp input file upload space, returning data product ids
- [x] helper function for adding files to user's tmp input file upload space
- [x] frontend needs to then pass these data product ids to experiment create
- [x] experiment create to use these data product ids - maptool can create the experiment and then redirect the user to the _edit experiment_ view
- [x] add some javascript variables to control the CPLEX application id and the generate_mps url, etc. so that the new code can be tested in beta while leaving the old code in place for the time being
- [x] update experiment_result and solution_summary to create scenario directory structure as needed
- [x] integrate Lower48US cost surface cache
- [x] implement candidate network generation in simccs_helper
- [x] refactor simccs_helper methods to take scenario_dir
- [x] update v1 layout code in _create_shapefiles_for_result to use simccs_helper
- [x] update v1 layout code in _load_solution to use simccs_helper
- [x] unit tests for simccs_helper.py and datasets.py
- ~~[ ] if user clicks cancel in "Generate MPS" modal, try to delete the sources, sinks and mps files (not strictly necessary, but this will clean these up if they aren't used)~~
  - decided to not implement this since it isn't necessary, and we may move away from this modal if and when we launch experiments directly from maptool
- [x] create a separate airavata-django-portal issue to develop an SDK. We'll move the stubbed SDK into that real SDK in the future.
  - https://issues.apache.org/jira/browse/AIRAVATA-3342
- [x] update production cplex app in simccs.org to have the new non-required inputs, so it is ready for these changes on dev

**Comment by machristie** [comment]
Here the JavaScript I run in the console to enable this feature on the beta site:
```javascript
Maptool.FeatureFlag.cloneable = {
  cplexApplicationId: "Cplex_new_0bc549cd-e07e-42b3-ae60-beeb19f1b9a2"
}
```

**Comment by machristie** [comment]
I've deployed this to the beta.simccs.scigap.org test site now. I updated the Cplex app to have the additional non-required inputs of Sources, Sinks and Dataset-id.

**Comment by machristie** [comment]
I've also updated the production (simccs.org) Cplex app as well.
