### ISSUE TITLE
Reuse candidate network when generating mps file

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#72]
The candidate network generation is the most costly part of generating an mps file. If the candidate network has already been generated, it makes sense to reuse that when generating the mps file.

One question is how to reuse it. A couple possibilities come to mind:
- have the frontend piece them together by first making a request for the candidate network, then pass that to the generate_mps call
- persist the candidate network in a database and pass back an identifier for it, passing the identifier on subsequent requests

### TODO
- [x] store the candidate network and the sources and sinks used in it
- [x] pass the candidate network to the generate_mps REST endpoint
- [x] evaluate performance in generating candidate network + generating mps (passing the candidate network) versus generating mps only (where candidate network has to be generated as part of generating mps)
- [x] in the UI, disable Generate Candidate Network button when sources and sinks haven't changed from last time candidate network was generated
- [x] See if we can use the candidate network from the community case studies if there isn't a user generated candidate network. Since the community case study candidate network includes all sources and sinks, it should be usable as is.

**Comment by machristie** [comment]
For now I'm planning on just returning to the frontend the candidate network text as a string.

Also will keep a set of source and sink ids for the candidate network. If the selected sources and sinks change, we can compare to the set of sources and sinks for the in memory candidate network to check to see if it needs to be regenerated.

**Comment by machristie** [comment]
Performance looks good. It takes as long to generate the candidate network first and then pass it to the mps generation as it takes to generate the mps without the candidate network. That's pretty much as expected, since the mps generation needs to generate the candidate network when it isn't given one.

This means we can break up the mps generation into a candidate network and then mps phase. Since the candidate network phase takes the longest by far (for SoutheastUS and all sources and sinks it takes ~14s whereas the MPS generation takes ~1s), we can let the user know that the candidate network is being generated and that it will take a while.
