### ISSUE TITLE
Add SimCCS Project to data model and API

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#95]
A SimCCS Project will encapsulate a set of datasets and cases that are shared with a group of users.

- each SimCCS Project is associated with an Airavata Project. This Airavata Project will be the project under which scenario experiments are created.
- members of the user group will have access to see all of the scenarios/experiments in the Airavata Project.
- the SimCCS Project can have an assigned Airavata Group of users who have READ permission to everything in the SimCCS Project.
- only the owner of the SimCCS Project can edit the project.
- the SimCCS Project owner can create an Airavata Group for the project and then delegate administration of the group (add/remove members) to another member of the group.
- the owner of the SimCCS Project can transfer ownership to another member of the group.
- a user who adds a dataset or case to the SimCCS Project is called the owner of that dataset or case. Only the owner of a dataset or case can edit it.
- the SimCCS Project owner can, if needed, assume ownership of any dataset or case. This is intended to be used when someone leaves the project but the datasets/cases they created need to be updated.
- non-owner group members may copy a dataset or case and edit their copy.

Related:
- we need a data model to associate an experiment to the case that was used to construct that scenario

## TODO:
- [x] add SimccsProject to data model
- [x] add SimccsProject to API responses
- [x] create Airavata Project when SimccsProject is created
- [x] manage group being assigned to SimccsProject, should share Airavata Project with group
- [x] add write authorization of SimccsProject, Case and Dataset based on ownership
- [x] add read authorization of Datasets, Cases based on group membership
- [x] implement API methods to transfer ownership of SimccsProject
- [x] implement API methods for SimccsProject owner to take ownership of Datasets, Cases
-  ~~implement API methods for copying Datasets, Cases~~ handled by UI
- ~~add model to associate scenarios and experiments with cases. Might be worth it to capture the model parameters on each experiment as well.~~ see Workspace data structure

**Comment by machristie** [comment]
Instead of having an API method to copy a Case, it's easier to just have the UI implement this functionality. The UI only needs to remove the Case id and then POST the JSON to make a copy of the Case.

For Dataset, I'm not sure yet if making a copy makes sense, so I'm going to leave that out for now. Once #85 is implemented and datasets can be updated, it may then make sense to create personal copies of datasets.

Also, the *model to associate scenarios and experiments with cases* I think will be handled by the [Workspace](https://github.com/SciGaP/simccs-maptool/wiki/Build-Tool:-Workspace) data model.
