### ISSUE TITLE
SimCCS Project UI

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#98]
Create a UI for creating/managing projects in the build tool

### TODO

- [x] make the top level UI based on the selected project, add a project selector
- [x] new project create view
- [x] add a project editor that can be used by project owner
- [x] group selector in project editor
- [x] change ownership of SimCCS Project
- [x] claim ownership of Project Cases and Datasets
- [x] option to copy a Case if not the owner
- [x] update dataset saving to save into project folder
- [x] buttons to create/edit group
- [x] list username of owner for non-owners to see
- [x] remember most recent project and default to viewing that one
